### ISSUE TITLE
Support dot access

### ISSUE THREAD

**Issue by Kikobeats** [posva/shapify#9]
```js
return shapify(
      {
        id: 'id',
        name: 'name',
        title: 'profile.title',
        displayName: 'real_name',
        timezone: 'tz'
      },
      user
    )
```

**Comment by posva** [comment]
Unfortunately, dot access cannot be made type-safe because it's a string. If you want dot access but do not care about type safety, I recommend you using something like `lodash.get` otherwise you have to use the [function version](https://github.com/posva/shapify#customizing-the-new-value):

```js
shapify(
  {
    title: user => user.profile.title
  },
  user
)
```
